stages:
  fetch_crypto_data:
    cmd: >
      poetry run python src/data/fetch_save.py
    deps:
      - src/data/fetch_save.py
    params:
      - fetch.url
    outs:
      - data/raw/crypto_prices.json
      - data/preprocessed/price:
          persist: true

    always_changed: true

  fetch_fear_greed_data:
    cmd: >
      poetry run python src/data/fetch_fear_greed.py
    deps:
      - src/data/fetch_fear_greed.py
      - params.yaml
    params:
      - fetch.fear_greed_url
      - preprocess.fear_greed_output_dir
      - preprocess.fear_greed_output_filename
    outs:
      - data/preprocessed/fear_greed:
          persist: true
    always_changed: true

  validate_data:
    cmd: >
      cd gx && poetry run python run_checkpoint.py fear_greed_checkpoint && poetry run python run_checkpoint.py solana_checkpoint && poetry run python run_checkpoint.py ethereum_checkpoint && poetry run python run_checkpoint.py bitcoin_checkpoint && cd ..
    deps:
      - gx/run_checkpoint.py
      - gx/checkpoints/fear_greed_checkpoint.yml
      - gx/checkpoints/solana_checkpoint.yml
      - gx/checkpoints/ethereum_checkpoint.yml
      - gx/checkpoints/bitcoin_checkpoint.yml
      - data/preprocessed/fear_greed/fear_greed_index.csv
      - data/preprocessed/price/solana.csv
      - data/preprocessed/price/ethereum.csv
      - data/preprocessed/price/bitcoin.csv
    outs:
      - gx/uncommitted/data_docs/local_site/validations/fear_greed_suite
      - gx/uncommitted/data_docs/local_site/validations/solana_suite
      - gx/uncommitted/data_docs/local_site/validations/ethereum_suite
      - gx/uncommitted/data_docs/local_site/validations/bitcoin_suite
    always_changed: true

  test_crypto_data:
    cmd: >
      poetry run python src/data/test_data.py
    deps:
      - src/data/test_data.py
      - data/preprocessed/price/bitcoin.csv
      - data/preprocessed/price/ethereum.csv
      - data/preprocessed/price/solana.csv
    outs:
      - reports/bitcoin_data_testing_report.html
      - reports/ethereum_data_testing_report.html
      - reports/solana_data_testing_report.html

  train_models:
    cmd: >
      poetry run python src/model/train_models.py
    deps:
      - src/model/train_models.py
      - data/preprocessed/price/bitcoin.csv
      - data/preprocessed/price/ethereum.csv
      - data/preprocessed/price/solana.csv
      - data/preprocessed/fear_greed/fear_greed_index.csv
    outs:
      - models/

  test_models:
    cmd: >
      poetry run python src/model/test_models.py
    deps:
      - src/model/test_models.py
      - models/
      - data/preprocessed/price/bitcoin.csv
      - data/preprocessed/price/ethereum.csv
      - data/preprocessed/price/solana.csv
      - data/preprocessed/fear_greed/fear_greed_index.csv
    outs:
      - predictions/bitcoin_prediction_nofng.csv
      - predictions/bitcoin_prediction_with_fng.csv
      - predictions/ethereum_prediction_nofng.csv
      - predictions/ethereum_prediction_with_fng.csv
      - predictions/solana_prediction_nofng.csv
      - predictions/solana_prediction_with_fng.csv
