stages:
  fetch_crypto_data:
    cmd: >
      poetry run python src/data/fetch_save.py
      git commit -am "Updated crypto data on `date` with DVC pipeline and GitHub workflows"
      2>$null
      git push 2>$null
      dvc push 2>$null
    deps:
    - src/data/fetch_save.py
    params:
    - fetch.url
    outs:
    - data/raw/crypto_prices.json
    - data/preprocessed/price:
        persist: true
    always_changed: true

  test_crypto_data:
    cmd: >
      poetry run python src/data/test_data.py
    deps:
    - src/data/test_data.py
    - data/preprocessed/price/bitcoin.csv
    - data/preprocessed/price/ethereum.csv
    - data/preprocessed/price/solana.csv
    outs:
    - reports/bitcoin_data_testing_report.html
    - reports/ethereum_data_testing_report.html
    - reports/solana_data_testing_report.html
