stages:
  fetch_and_preprocess:
    cmd: >
      poetry run python src/data/fetch_save.py
      git commit -am "Updated crypto data on `date` with DVC pipeline and GitHub workflows" 2>$null
      git push 2>$null
      dvc push 2>$null
    deps:
      - src/data/fetch_save.py
    params:
      - fetch.url
    outs:
      - data/raw/crypto_prices.json
      - data/preprocessed/price:
          persist: true
    always_changed: true
