fetch:
  url: "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,solana&vs_currencies=usd"

preprocess:
  cryptocurrencies:
    - bitcoin
    - ethereum
    - solana
  output_dir: "data/preprocessed/price"
  raw_dir: "data/raw"
  raw_filename: "crypto_prices.json"
